### ISSUE TITLE
Still missing some underscores + no check if variable is not empty

### ISSUE THREAD

**Issue by gial11** [bdaiinstitute/spot_wrapper#9]
- Missing underscores:
    - [here](https://github.com/bdaiinstitute/spot_wrapper/blob/22cf994b97a8ff1da26b5bd68edf512e13ac0eee/spot_wrapper/wrapper.py#L372) it should be `self._spot_wrapper._is_standing`
    - [here](https://github.com/bdaiinstitute/spot_wrapper/blob/22cf994b97a8ff1da26b5bd68edf512e13ac0eee/spot_wrapper/wrapper.py#L374) it should be `self._spot_wrapper._is_moving`
    - [here](https://github.com/bdaiinstitute/spot_wrapper/blob/22cf994b97a8ff1da26b5bd68edf512e13ac0eee/spot_wrapper/wrapper.py#L965) it should be `self._lease`.

- [Here](https://github.com/bdaiinstitute/spot_wrapper/blob/22cf994b97a8ff1da26b5bd68edf512e13ac0eee/spot_wrapper/wrapper.py#L965) there is no check if `self._lease` is empty (because if it is, for example before initialisation, the for loop will raise an error).

**Comment by heuristicus** [comment]
The missing underscores are using the object properties to access the variables, but it should probably refer to them directly. The lease thing might be worth a check, but because the async lease is always running the object will probably never be none.

**Comment by gial11** [comment]
Thank you for the answer. Did you tested it with a real spot? Because with our spot the driver fail to launch if we do not add the check for an empty variable (it complains that NoneType is not iterable).

**Comment by gial11** [comment]
Fixed in commit 8de0476.
